commandsPostDeploy:
  - id: c0d50a8e-e4d4-4b5f-9de3-8af22aded00b
    label: Import Handover checklist reference data
    type: data
    command: ""
    parameters:
      sfdmuProject: HeliosHandoverRefData
    runOnlyOnceByOrg: true
    context: process-deployment-only
commandsPreDeploy:
  - id: 7ac139eb-b547-4d1f-93c1-eff18f5e4e0c
    label: Exclude Helios Crew from deployment
    type: remove-packagexml-items
    command: ""
    parameters:
      packageXmlItems:
        - Profile:Helios Crew
    runOnlyOnceByOrg: true
    context: all
