commandsPostDeploy:
  - id: 570b4dac-4380-42a7-bd51-43172fa63c33
    label: Backfill Crew Size on existing installations
    type: apex
    command: ""
    parameters:
      apexScript: scripts/apex/backfill-crew-size.apex
    runOnlyOnceByOrg: true
    context: process-deployment-only
